package com.example.demoVanillaJava.api.rest.swagger;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.media.*;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import io.swagger.v3.oas.models.tags.Tag;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class OpenApiGenerator {

    private static final OpenAPI openApi = new OpenAPI()
            .info(new Info()
                    .title("User Management API")
                    .version("1.0.0")
                    .contact(new Contact()
                            .name("Support Team")
                            .email("support@example.com")
                            .url("https://example.com"))
                    .license(new License()
                            .name("Apache 2.0")
                            .url("http://www.apache.org/licenses/LICENSE-2.0.html")))
            .servers(Collections.singletonList(
                    new Server()
                            .url("http://localhost:8080")
                            .description("Local development server")
            ))
            .tags(Arrays.asList(
                    new Tag().name("login").description("Логин"),
                    new Tag().name("user").description("Операции с пользователями"),
                    new Tag().name("kafka").description("Операции с кафкой"),
                    new Tag().name("redis").description("Операции с редис"),
                    new Tag().name("prometheus").description("Операции с метриками")
            ))
            .components(new Components()
                    .schemas(Map.of(
                            "LoginDto", new Schema<>()
                                    .type("object")
                                    .addProperties("login", new StringSchema())
                                    .addProperties("password", new StringSchema()),
                            "CreateUserDto", new Schema<>()
                                    .type("object")
                                    .addProperties("login", new StringSchema())
                                    .addProperties("password", new StringSchema())
                                    .addProperties("name", new StringSchema()),
                            "UserDto", new Schema<>()
                                    .type("object")
                                    .addProperties("id", new IntegerSchema().format("int64"))
                                    .addProperties("login", new StringSchema())
                                    .addProperties("password", new StringSchema())
                                    .addProperties("name", new StringSchema()),
                            "CounterDto", new Schema<>()
                                    .type("object")
                                    .addProperties("name", new StringSchema())
                                    .addProperties("tags", new ArraySchema().items(new Schema<>().$ref("#/components/schemas/TagDto"))),
                            "TagDto", new Schema<>()
                                    .type("object")
                                    .addProperties("name", new StringSchema())
                                    .addProperties("value", new StringSchema())
                    ))
                    .securitySchemes(Map.of(
                            "Authorization", new SecurityScheme()
                                    .type(SecurityScheme.Type.APIKEY)
                                    .name("Authorization")
                                    .in(SecurityScheme.In.HEADER))))
            .addSecurityItem(new SecurityRequirement()
                    .addList("Authorization"))
            .path("/user", new PathItem()
                    .get(new Operation()
                            .tags(List.of("user"))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                            .content(new Content()
                                                    .addMediaType("application/json", new MediaType()
                                                            .schema(new Schema<>().$ref("#/components/schemas/UserDto"))
                                                    )))))
                    .post(new Operation()
                            .tags(List.of("user"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/CreateUserDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    )))
                    .put(new Operation()
                            .tags(List.of("user"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/UserDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    )))
                    .delete(new Operation()
                            .tags(List.of("user"))
                            .addParametersItem(new Parameter()
                                    .name("id")
                                    .in("query")
                                    .required(true)
                                    .schema(new Schema<>()
                                            .type("string"))
                            )
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    ))))
            .path("/sendIntoKafka", new PathItem()
                    .post(new Operation()
                            .tags(List.of("kafka"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("text/plain", new MediaType()
                                                    .schema(new Schema<>().type("string"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    ))))
            .path("/redis", new PathItem()
                    .get(new Operation()
                            .tags(List.of("redis"))
                            .addParametersItem(new Parameter()
                                    .name("key")
                                    .in("query")
                                    .required(true)
                                    .schema(new StringSchema())
                            )
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    )))
                    .post(new Operation()
                            .tags(List.of("redis"))
                            .addParametersItem(new Parameter()
                                    .name("key")
                                    .in("query")
                                    .required(true)
                                    .schema(new StringSchema())
                            )
                            .addParametersItem(new Parameter()
                                    .name("value")
                                    .in("query")
                                    .required(true)
                                    .schema(new StringSchema())
                            )
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    )))
                    .put(new Operation()
                            .tags(List.of("redis"))
                            .addParametersItem(new Parameter()
                                    .name("key")
                                    .in("query")
                                    .required(true)
                                    .schema(new StringSchema())
                            )
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    ))))
            .path("/prometheus", new PathItem()
                    .post(new Operation()
                            .tags(List.of("prometheus"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/CounterDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    )))
                    .put(new Operation()
                            .tags(List.of("prometheus"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/CounterDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    ))))
            .path("/prometheus/get", new PathItem()
                    .post(new Operation()
                            .tags(List.of("prometheus"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/CounterDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                    ))))
            .path("/login", new PathItem()
                    .post(new Operation()
                            .tags(List.of("login"))
                            .requestBody(new RequestBody()
                                    .content(new Content()
                                            .addMediaType("application/json", new MediaType()
                                                    .schema(new Schema<>().$ref("#/components/schemas/LoginDto"))
                                            )))
                            .responses(new ApiResponses()
                                    .addApiResponse("200", new ApiResponse()
                                            .description("OK")
                                            .content(new Content()
                                                    .addMediaType("application/json", new MediaType()
                                                            .schema(new StringSchema())
                                                    ))
                                    ))));

    public static OpenAPI createOpenAPI() {
        return openApi;
    }
}